### PR TITLE
Add completions for additional `gh pr` subcommands

### PR DESCRIPTION
**Pull request by hexium310**
This PR adds completions for the following `gh pr` subcommands added to `gh` since #107.

- checks
- lock
- unlock

### CODE REVIEW

**Comment by chitoku-k** [comment]
Please sort test cases by their subcommand name in alphabetical order.

**Comment by hexium310** [comment]
Do you want me to sort the existing test cases too?

**Comment by chitoku-k** [comment]
They are currently sorted in the order they are implemented. Just swap `lock` and `unlock` should be enough.

**Review by chitoku-k — APPROVED** [review]
Legit!

**Pull request merged**
