### PR TITLE
Show kind of ref object

### LINKED ISSUE #45: Show ref object type in the commit list
The current object list lacks what kind of ref object they are as follows:

```zsh
$ git rebase **
>
  5/5
> another-branch   2nd commit
  master          1st commit
  v1              1st commit
  v2               2nd commit
  3e209a3         1st commit
```

To effectively filter those references, object types (printed in green) can be shown like this:

```zsh
$ git rebase **
>
  5/5
> another-branch  branch   2nd commit
  master          branch  1st commit
  v1              tag     1st commit
  v2              tag      2nd commit
  3e209a3         commit  1st commit
```

which results in:

```zsh
$ git rebase another-branch
```

### PR DESCRIPTION
**Pull request by himanoa**
fix #45 

## Screenshot

Feb-12-2020 05-21-52

### CODE REVIEW

**Comment by chitoku-k** [comment]
Almost thbre! Some of the tests are failing because all of the similar occurrences have to be fixed.

**Comment by chitoku-k** [comment]
The following assertions passed with the current implementation:
```
assert ${lines[1]} same_as "${fg[yellow]}another-branch ${fg[green]}branch$reset_color   2nd commit"
assert ${lines[2]} same_as "${fg[yellow]}master         ${fg[green]}branch$reset_color  1st commit"
assert ${lines[3]} same_as "${fg[yellow]}v1             ${fg[green]}tag$reset_color     1st commit"
assert ${lines[4]} same_as "${fg[yellow]}v2             ${fg[green]}tag$reset_color      2nd commit"
assert ${lines[5]} same_as "${fg[yellow]}3e209a3        ${fg[green]}commit$reset_color  1st commit"
```

**Comment by chitoku-k** [comment]
You can just use `%6s` as a format for the kind because `branch` and `tag` are constants.

**Comment by hexium310** [comment]
@himanoa The generic tabularize function is added by #61. You can easily implement it by replacing `_fzf_complete_git_tabularize` to `_fzf_complete_tabularize ${fg[yellow]} ${fg[green]}`.

**Comment by chitoku-k** [comment]
Will be continued in #72!

**Pull request closed without merging**
